# Generated by Django 5.0 on 2023-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('granted', 'Deferido'), ('rejected', 'Indeferido'), ('in_progress', 'Aguardando Resposta')], default='Aguardando Resposta', max_length=20, verbose_name='Status:'),
        ),
    ]
