# Generated by Django 5.0 on 2023-12-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_rename_end_time_event_end_and_more'),
        ('reservation', '0007_alter_reservation_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation', verbose_name='Reserva do evento'),
            preserve_default=False,
        ),
    ]
