# Generated by Django 5.0 on 2023-12-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_event_id_reservation_alter_event_status_and_more'),
        ('rooms', '0006_alter_room_available_alter_room_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Sala'),
            preserve_default=False,
        ),
    ]
