# Generated by Django 5.0 on 2023-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_event_id_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='class_school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma:'),
        ),
    ]
