# Generated by Django 4.2.6 on 2023-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='matricula',
            new_name='registration',
        ),
        migrations.AddField(
            model_name='user',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='Coordinator status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Admin status'),
        ),
    ]
