# Generated by Django 4.2.6 on 2023-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('student', 'Aluno'), ('coordinator', 'Coordenador'), ('teacher', 'Professor')], default='student', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Teacher'),
        ),
    ]
