# Generated by Django 5.0 on 2023-12-15 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('key', models.CharField(max_length=100, verbose_name='Chave da Sala')),
                ('department', models.CharField(choices=[('administration', 'Bloco 01 - Direção'), ('main_building', 'Bloco 02 - Principal'), ('laboratories', 'Bloco 03 - Laboratórios'), ('dining_sector', 'Bloco 04 - Setor de Alimentação'), ('library', 'Bloco 05 - Biblioteca'), ('health_sector', 'Bloco 06 - Setor de Saúde'), ('sports_gymnasium', 'Bloco 07 - Ginásio Poliesportivo'), ('garage', 'Bloco 08 - Garagem'), ('pool_and_field', 'Bloco 09 - Piscina e Campo'), ('classrooms', 'Bloco 10 - Salas de Aula'), ('honey_house', 'Bloco 11 - Casa do Mel'), ('apiary', 'Bloco 12 - Apiário'), ('vocational_training_center', 'Bloco 13 - CVT'), ('campus_territory', 'Território do Campus')], max_length=100, verbose_name='Prédio:')),
                ('available', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('progress', 'Em Andamento')], max_length=25, verbose_name='Agendável')),
                ('id_user_coordinator', models.ManyToManyField(limit_choices_to={'registration_type': 'coordinator'}, related_name='coordinator_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador de Agendamentos')),
            ],
        ),
    ]
