# Generated by Django 5.0 on 2023-12-25 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=25, verbose_name='Agendável'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id_user_coordinator',
            field=models.ManyToManyField(blank=True, limit_choices_to={'registration_type': 'coordinator'}, null=True, related_name='coordinator_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador de Agendamentos'),
        ),
    ]
