# Generated by Django 4.2.7 on 2023-11-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='sala',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='room',
            name='predio',
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Sala disponível'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.CharField(blank=True, choices=[('Bloco 01 - Direção', 'Bloco 01 - Direção'), ('Bloco 02 - Principal', 'Bloco 02 - Principal'), ('Bloco 03 - Laboratórios', 'Bloco 03 - Laboratórios'), ('Bloco 04 - Setor de Alimentação', 'Bloco 04 - Setor de Alimentação'), ('Bloco 05 - Biblioteca', 'Bloco 05 - Biblioteca'), ('Bloco 06 - Setor de Saúde', 'Bloco 06 - Setor de Saúde'), ('Bloco 07 - Ginásio Poliesportivo', 'Bloco 07 - Ginásio Poliesportivo'), ('Bloco 08 - Garagem', 'Bloco 08 - Garagem'), ('Bloco 09 - Piscina e Campo', 'Bloco 09 - Piscina e Campo'), ('Bloco 10 - Salas de Aula', 'Bloco 10 - Salas de Aula'), ('Bloco 11 - Casa do Mel', 'Bloco 11 - Casa do Mel'), ('Bloco 12 - Apiário', 'Bloco 12 - Apiário'), ('Bloco 13 - CVT', 'Bloco 13 - CVT'), ('Território do Campus', 'Território do Campus')], max_length=100, null=True, verbose_name='Prédio:'),
        ),
        migrations.AddField(
            model_name='room',
            name='id_user_coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'registration_type': 'coordinator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave da Sala'),
        ),
    ]
