# Generated by Django 4.2.7 on 2023-11-28 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_rename_sala_room_room_name_remove_room_chave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5, null=True, verbose_name='Agendável'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id_user_coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'registration_type': 'coordinator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador de Agendamentos'),
        ),
    ]
