# Generated by Django 4.2.6 on 2023-12-01 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_rename_sala_room_room_name_remove_room_chave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.CharField(blank=True, choices=[('yes', 'Sim'), ('no', 'Não'), ('progress', 'Em Andamento')], max_length=25, null=True, verbose_name='Agendável'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.CharField(blank=True, choices=[('main_building', 'Bloco 02 - Principal'), ('administration', 'Bloco 01 - Direção'), ('laboratories', 'Bloco 03 - Laboratórios'), ('dining_sector', 'Bloco 04 - Setor de Alimentação'), ('library', 'Bloco 05 - Biblioteca'), ('health_sector', 'Bloco 06 - Setor de Saúde'), ('sports_gymnasium', 'Bloco 07 - Ginásio Poliesportivo'), ('garage', 'Bloco 08 - Garagem'), ('pool_and_field', 'Bloco 09 - Piscina e Campo'), ('classrooms', 'Bloco 10 - Salas de Aula'), ('honey_house', 'Bloco 11 - Casa do Mel'), ('apiary', 'Bloco 12 - Apiário'), ('vocational_training_center', 'Bloco 13 - CVT'), ('campus_territory', 'Território do Campus')], max_length=100, null=True, verbose_name='Prédio:'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id_user_coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'registration_type': 'coordinator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador de Agendamentos'),
        ),
    ]
