# Generated by Django 4.2.6 on 2023-12-01 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0005_alter_room_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('progress', 'Em Andamento')], max_length=25, verbose_name='Agendável'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.CharField(choices=[('administration', 'Bloco 01 - Direção'), ('main_building', 'Bloco 02 - Principal'), ('laboratories', 'Bloco 03 - Laboratórios'), ('dining_sector', 'Bloco 04 - Setor de Alimentação'), ('library', 'Bloco 05 - Biblioteca'), ('health_sector', 'Bloco 06 - Setor de Saúde'), ('sports_gymnasium', 'Bloco 07 - Ginásio Poliesportivo'), ('garage', 'Bloco 08 - Garagem'), ('pool_and_field', 'Bloco 09 - Piscina e Campo'), ('classrooms', 'Bloco 10 - Salas de Aula'), ('honey_house', 'Bloco 11 - Casa do Mel'), ('apiary', 'Bloco 12 - Apiário'), ('vocational_training_center', 'Bloco 13 - CVT'), ('campus_territory', 'Território do Campus')], max_length=100, verbose_name='Prédio:'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id_user_coordinator',
            field=models.ManyToManyField(limit_choices_to={'registration_type': 'coordinator'}, related_name='coordinator_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador de Agendamentos'),
        ),
        migrations.AlterField(
            model_name='room',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Chave da Sala'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100, verbose_name='Nome da Sala'),
        ),
    ]
