# Generated by Django 4.2.6 on 2023-11-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('justification', models.CharField(choices=[('Aula', 'Aula'), ('Trabalho', 'Trabalho'), ('Reunião', 'Reunião')], max_length=20)),
                ('annex', models.FileField(blank=True, null=True, upload_to='reservation_annex/')),
                ('message', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
