# Generated by Django 5.0 on 2023-12-15 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Data:')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário Final')),
                ('justification', models.TextField(max_length=200, verbose_name='Justificativa:')),
                ('class_school', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma:')),
                ('periodicity', models.CharField(blank=True, choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, null=True, verbose_name='Periodicidade:')),
                ('annex', models.FileField(blank=True, null=True, upload_to='reservation_annex/', verbose_name='Anexo:')),
                ('message', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mensagem:')),
                ('reply', models.CharField(blank=True, max_length=150, null=True, verbose_name='Resposta:')),
                ('status', models.CharField(choices=[('granted', 'Deferido'), ('rejected', 'Indeferido'), ('in_progress', 'Aguardando Resposta')], max_length=20, verbose_name='Status:')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Sala')),
                ('id_user_teacher', models.ForeignKey(limit_choices_to={'registration_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
        ),
    ]
