# Generated by Django 4.2.6 on 2023-11-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_rooms_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_user_coordinator',
            field=models.ManyToManyField(limit_choices_to={'registration_type': 'coordinator'}, null=True, related_name='coordinator_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_user_teacher',
            field=models.ForeignKey(limit_choices_to={'registration_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reply',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
