# Generated by Django 5.0 on 2023-12-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mensagem ao Solicitante:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reply',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mensagem ao Responsável:'),
        ),
    ]
