# Generated by Django 4.2.6 on 2023-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_id_room_reservation_id_user_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id_user_coordinator',
        ),
        migrations.AddField(
            model_name='reservation',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('Diária', 'Diária'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], max_length=20, null=True, verbose_name='Periodicidade:'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('Deferido', 'Deferido'), ('Indeferido', 'Indeferido'), ('Aguardando Resposta', 'Aguardando Resposta')], max_length=20, null=True, verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='reservation_annex/', verbose_name='Anexo:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='justification',
            field=models.CharField(blank=True, choices=[('Aula', 'Aula'), ('Trabalho', 'Trabalho'), ('Reunião', 'Reunião')], max_length=20, null=True, verbose_name='Justificativa:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mensagem:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reply',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Resposta:'),
        ),
    ]
