# Generated by Django 4.2.6 on 2023-12-01 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_available_alter_room_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_remove_reservation_id_user_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_user_teacher',
            field=models.ForeignKey(limit_choices_to={'registration_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='justification',
            field=models.CharField(choices=[('Aula', 'Aula'), ('Trabalho', 'Trabalho'), ('Reunião', 'Reunião')], max_length=20, verbose_name='Justificativa:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Deferido', 'Deferido'), ('Indeferido', 'Indeferido'), ('Aguardando Resposta', 'Aguardando Resposta')], max_length=20, verbose_name='Status:'),
        ),
    ]
