# Generated by Django 4.2.7 on 2023-12-04 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_available_alter_room_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0004_alter_reservation_id_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='endTime',
            field=models.TimeField(verbose_name='Horário Final'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_user_teacher',
            field=models.ForeignKey(limit_choices_to={'registration_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.TimeField(verbose_name='Horário de Início'),
        ),
    ]
