# Generated by Django 4.2.7 on 2023-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_date_alter_reservation_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, verbose_name='Data:'),
        ),
    ]
