# Generated by Django 5.0 on 2023-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='justification',
            field=models.CharField(choices=[('class', 'Aula'), ('work', 'Trabalho'), ('meeting', 'Reunião')], max_length=20, verbose_name='Justificativa:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, null=True, verbose_name='Periodicidade:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('granted', 'Deferido'), ('rejected', 'Indeferido'), ('in_progress', 'Aguardando Resposta')], max_length=20, verbose_name='Status:'),
        ),
    ]
