# Generated by Django 5.0 on 2023-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_justification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='justification',
            field=models.CharField(max_length=200, verbose_name='Justificativa:'),
        ),
    ]
