# Generated by Django 5.0 on 2023-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_reservation_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='class_school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma:'),
        ),
    ]
